# Configuração de marcação e linguagem
highlighter: rouge
paginate: 5
language: 'pt-br'

# Informação do blog
name: 'Allan Ramos'
description: "Programação com um pouco de café."

# Informação do autor
author: 'Allan Ramos'
nickname: presto
bio: 'Um nerd caiçara que gosta de programar e também de outras aí.'
location: 'São Paulo, Brasil'

# Configuração do blog
url: 'https://allangrds.github.io'
image: 'assets/images/presto.png'
google_analytics: UA-69281367-1
disqus: allangrds
baseurl: '/blog/'
permalink: /:title
gems: [jekyll-paginate]
exclude: [vendor]
disqus:
  shortname: allangrds