# Site settings
title: Allan Ramos
description: A blog about lorem ipsum dolor sit amet
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://allangrds.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Allan Ramos
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Desenvolvedor web
email: allangabrielrds@gmail.com
twitter_username: allangrds
github_username:  allangrds
gplus_username:  allangrds
disqus_username: allan_ramos

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /blog/series
  - title: Tags
    url: /blog/tags
  - title: About Me
    url: /blog/about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
